version: '3.8'

services:
  app:
    container_name: svelte-application
    restart: on-failure
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - $LOCAL_PORT:$DOCKER_PORT